name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:

  security-scan:

    runs-on: ubuntu-latest

    steps:

      # =========================
      # CHECKOUT CODE
      # =========================

      - name: Checkout Code
        uses: actions/checkout@v4

      # =========================
      # VERIFY FILES
      # =========================

      - name: List Repository Files
        run: |
          pwd
          ls -la
          find . -name "requirements.txt"

      # =========================
      # PYTHON SETUP
      # =========================

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # =========================
      # INSTALL DEPENDENCIES
      # =========================

      - name: Install Requirements
        run: |
          pip install -r requirements.txt || true

      # =========================
      # TRIVY SAST + SECRETS
      # =========================

      - name: Run Trivy Scan

        uses: aquasecurity/trivy-action@master

        continue-on-error: true

        with:
          scan-type: 'fs'
          scan-ref: '.'

          format: 'json'

          output: 'trivy-results.json'

          severity: 'MEDIUM,HIGH,CRITICAL'

          exit-code: '1'

      # =========================
      # OWASP DEPENDENCY CHECK
      # =========================

      - name: Run Dependency Check

        uses: dependency-check/Dependency-Check_Action@main

        continue-on-error: true

        with:
          project: 'DevSecOps'

          path: '.'

          format: 'JSON'

          out: 'reports'

      # =========================
      # SHOW REPORT FILES
      # =========================

      - name: Verify Reports
        run: |
          find . -name "*.json"
          ls -la reports || true

      # =========================
      # UPLOAD TRIVY REPORT
      # =========================

      - name: Upload Trivy Report

        uses: actions/upload-artifact@v4

        with:
          name: trivy-report

          path: trivy-results.json

      # =========================
      # UPLOAD DEPENDENCY REPORT
      # =========================

      - name: Upload Dependency Report

        uses: actions/upload-artifact@v4

        with:
          name: dependency-check-report

          path: reports/dependency-check-report.json
